# Name of the action visible in the action overview
name: updates tokens sent from figma
# this triggers the action when a post to "https://api.github.com/repos/:username/:repo/dispatches" comes in
on:
  repository_dispatch:
    # the event_type property from the request body is 'update-tokens'
    types: update-tokens
    
jobs:
  build:
    # the name for the entire job
    name: Transform Figma design tokens
    # we run this on ubuntu, leave this alone, if you don't have a good reason to change it
    runs-on: ubuntu-latest
    steps:
      # this lets us work in the actual repository 
      - uses: actions/checkout@master
      - name: mkdir "tokens" directory
        # change tokens here (and in line 32) if you want to use a differently named folder 
        run: 'mkdir -p tokens'
      - name: create json from request body
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ github.event.client_payload.filename }}
          json: ${{ github.event.client_payload.tokens }}
          dir: 'tokens'
      # we now initialize node to run amazon style dictionary to compile the tokens
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Transform design tokens by running the transform script
        run: 'npm i && npm run transform-tokens'

      - name: Remove unnecessary tokens directory
        run: rm -rf tokens

      - name: Create PR 
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Tokens updated"
          title: "Design tokens updated"
          body: "Design tokens have been updated via Figma and need to be reviewed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # this parameter is optional and defaults to master
          BRANCH_NAME: 'main'
